name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "Mirage007"
          GITHUB_TOKEN: ${{secrets.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}}
